service: harryng-serverless
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource:
        - arn:aws:dynamodb:ap-southeast-2:819809268659:table/WorksTable

functions:
  addWork:
    handler: src/routes/works/addWork.handler
    events:
      - http:
          path: /works/add-work
          method: post
  fetchWorks:
    handler: src/routes/works/fetchWorks.handler
    events:
      - http:
          path: /works/list-works
          method: get
  fetchWork:
    handler: src/routes/works/fetchWork.handler
    events:
      - http:
          path: /works/work-detail/{id}
          method: get
  deleteWork:
    handler: src/routes/works/deleteWork.handler
    events:
      - http:
          path: /works/delete-work/{id}
          method: delete
  uploadImageWork:
    handler: src/routes/works/uploadImageWork.handler
    events:
      - http:
          path: /works/upload-image-work
          method: post
  deleteImageWork:
    handler: src/routes/works/deleteImageWork.handler
    events:
      - http:
          path: /works/delete-image-work/{fileKey}
          method: delete
  updateWork:
    handler: src/routes/works/updateWork.handler
    events:
      - http:
          path: /works/update-work
          method: post

resources:
  Resources:
    WorksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WorksTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline
